---

- name: Change hostname for rsyslog
  hostname:
    name: "{{ hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ hostname }}'
    state: present

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1[ \t]+stretch'
    line: '127.0.1.1  {{ hostname }}.localdomain  {{ hostname }}'
    state: present
