---

- name: Set rsyslog config file
  become: yes
  template:
    src: rsyslog.j2
    dest: /etc/rsyslog.conf

- name: Stop Syslog service
  systemd:
    state: stopped
    name: syslog

- name: Restart rsyslog service
  systemd:
    state: restarted
    daemon_reload: yes
    name: rsyslog
