---
- name: install rsyslog package
  apt:
    name: rsyslog
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - rsyslog
    - rsyslog-install
