---
- name: install
  apt:
    name: rsyslog
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - rsyslog
    - rsyslog-install

- name: Set rsyslog config file
  become: yes
  template:
    src: rsyslog.j2
    dest: /etc/rsyslog.conf

- name: Restart rsyslog service
  systemd:
    state: restarted
    daemon_reload: yes
    name: rsyslog
