---
- hosts: centralized
  become: true
  
# tasks: 
#   - name: Set a hostname
#     hostname:
#       name: "webserver"
#
#   - name: add hostname to /etc/hosts
#     lineinfile:
#       dest: /etc/hosts
#       regexp: '^127\.0\.0\.1[ \t]+localhost'
#       line: '127.0.0.1 localhost webserver'
#       state: present

  roles:
    - role: ssh-keys
      tag: ssh

    - role: default-apps
      tag: apps

    - role: networking
      tag: networking
