---
- hosts: centralized
  become: true
  
  roles:
    - role: hostname
      tah: hostname

    - role: ssh-keys
      tag: ssh

    - role: default-apps
      tag: apps

    - role: networking
      tag: networking

