---
- hosts: log-server
  become: true

  tasks: 
    - name: Set a hostname
      hostname:
        name: "log-server"

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost log-server'
        state: present

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.1\.1[ \t]+localhost'
        line: '127.0.1.1 localhost log-server'
        state: present
