---
- hosts: server01
  become: true

  
  tasks: 
    - name: Set a hostname
      hostname:
        name: "server01"

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost server01'
        state: present

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.1\.1[ \t]+localhost'
        line: '127.0.1.1 localhost server01'
        state: present
  
  roles:
    - role: rsyslog-client
