---
 - name: Install packages
   apt: name={{ item }} state=present
   with_items:
     - git
     - htop
     - tree  
     - net-tools
     - vim
     - ufw
     - make


- name: install Rsyslog Package
  apt:
    name: rsyslog
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - rsyslog
    - rsyslog-install
